data:
  data_layer: null 
  init_params:
    vocab: "demo/data/imdb.vocab"
    labels_vocab: ["pos", "neg"]
    unk_id: 0
  train:
    features_source: "demo/data/reviews.txt"
    labels_source: "demo/data/labels.txt"
  dev:
    features_source: "demo/data/reviews.txt"
    labels_source: "demo/data/labels.txt"    